// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package test

// schema: com.test.feed.getPosts

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// FeedGetPosts_Output is the output of a com.test.feed.getPosts call.
type FeedGetPosts_Output struct {
	Posts []*FeedDefs_PostView `json:"posts" cborgen:"posts"`
}

// FeedGetPosts calls the XRPC method "com.test.feed.getPosts".
//
// uris: List of post at-uris to returned hydrated views for.
func FeedGetPosts(ctx context.Context, c *xrpc.Client, uris []string) (*FeedGetPosts_Output, error) {
	var out FeedGetPosts_Output

	params := map[string]interface{}{
		"uris": uris,
	}
	if err := c.Do(ctx, xrpc.Query, "", "com.test.feed.getPosts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
