// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package test

// schema: com.test.feed.defs

import (
	"github.com/bluesky-social/indigo/lex/util"
)

// FeedDefs_PostView is a "postView" in the com.test.feed.defs schema.
type FeedDefs_PostView struct {
	Cid    string                   `json:"cid" cborgen:"cid"`
	Record *util.LexiconTypeDecoder `json:"record" cborgen:"record"`
	Uri    string                   `json:"uri" cborgen:"uri"`
}
