// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package test

// schema: com.test.feed.post

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("com.test.feed.post", &FeedPost{})
} //
// RECORDTYPE: FeedPost
type FeedPost struct {
	LexiconTypeID string `json:"$type,const=com.test.feed.post" cborgen:"$type,const=com.test.feed.post"`
	// createdAt: Client-declared time of when the recipe was created.
	CreatedAt *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Text      *string `json:"text,omitempty" cborgen:"text,omitempty"`
}
